spring:
  data:
    mongodb:
      database: salerev
      uri: mongodb://mongo:27017
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: salesianas.nervion.reservas@gmail.com
    password: Salesianas1234*
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          writetimeout: 5000